### ISSUE TITLE
TODO: Project Set-up

### ISSUE THREAD

**Issue by callahantiff** [henrylittle21/SRS-NLP#1]
## TODO: Project Set-Up     
**Purpose:** Describe tasks that need to be completed to get this repo set-up for your 🥇 awesome science fair project 🎉   
**Assigned To:** @henrylittle21 

**Overview:**  
Great meeting today and congrats on your first GitHub repository as well as the beginnings of what will be an awesome science fair project! As we discussed today, the goal for the next week is to start getting this repository organized and set-up for your project. Additionally, as shown below, this week will also be focused on learning more about NLP and language models. 

Below, are the tasks I am hoping you will be able to make progress on before our next meeting (scheduled for **10/3/19**).  

___

### TODO List   
**GitHub Repository Tasks:**  
  - [x] Get more familiar with how GitHub works and what you can do with by reviewing these:  
    - [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)  
    - [Mastering Issues](https://guides.github.com/features/issues/)      
    - [Documenting your projects](https://guides.github.com/features/wikis/)  
    - [Understand how to interact with other Projects](https://guides.github.com/activities/socialize/)    
    - [Using GitHub for Research](https://github.com/callahantiff/PheKnowLator/wiki/Using-GitHub-as-a-Reproducible-Research-Platform)    
  - [x]  Set-up your project Wiki Page (**FIRST** think through how you might want to organize things and what might be important to have as sub-pages)      
    -  Useful resources:  
       - See [this](https://help.github.com/en/articles/adding-or-editing-wiki-pages) guide on Wikis and how to use them in GitHub  
      - Find good examples. [PheKnowLator](https://github.com/callahantiff/PheKnowLator/wiki) is one of my projects. You can see how I have organized my Wiki.  
  - [x] Think about who else you might want to add as collaborators. You may want to hold off on adding them until you get your Wiki page set-up, but in the meantime, generate list of people you think would be good to add.  
  - [ ] Create some project Milestones (information on how to do this can be found [here](https://help.github.com/en/articles/about-milestones)) for your project. I would recommend creating a milestone for all important due dates and deadlines.  [Here](https://github.com/henrylittle21/SRS-NLP/milestone/1) is an example of a Milestone I have created for you.  

**Project Tasks:**  
- [ ] Read over these comprehensive Python+NLP tutorials. Don't worry about doing them (yet ;D), I just want you to get a feel for what NLP data workflows look like and what you can do with existing tools:  
  - An Introduction to NLP on Medium - [here](https://towardsdatascience.com/a-practitioners-guide-to-natural-language-processing-part-i-processing-understanding-text-9f4abfd13e72)      
  - [Gentle Introduction to Language Models](https://machinelearningmastery.com/statistical-language-modeling-and-neural-language-models/)  
  - [Introduction to Natural Language Processing: Part 1](https://medium.com/analytics-vidhya/introduction-to-natural-language-processing-part-1-777f972cc7b3)  
  - [Learning NLP Language Models with Real Data ](https://towardsdatascience.com/learning-nlp-language-models-with-real-data-cdff04c51c25)   
- [x] Review these articles on language models. Don't worry about understanding every detail, instead just try to focus on learning more about how they work and what they can be used for.  
  - [GPT-2](https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf)  
  - [BERT](https://arxiv.org/abs/1810.04805)     
  - Are there other language models you can find and that you might be interested? If so, which ones?  
- [x] Start looking for data. Like we discussed today, start finding examples of descriptions of science fair projects. This does not have to be limited to high school projects and should include examples from other schools, states, or even other countries (if you come across any during your research).  
  - Create a Google Sheet to store the data you find and make sure your team has access to it. You might want to consider adding the following columns to your spreadsheet:  
    - A Link or URL to where you found the data   
    - Number of examples the data contains (i.e. how many projects)  
    - Data-level (i.e. does the source only include project titles, or does it also include project descriptions, awards or placings, and grade level)   
     - School name  
     - Year of science fair  
     - Add other information you think might be useful!     

___   

I'm happy to help if you get stuck! If you have questions about anything above, you can respond within this issues and I will be notified. You can also specifically mention me in an issue by including `@callahantiff` in the text.  

Good Luck and have fun with this!

**Comment by callahantiff** [comment]
@jackstolt - thanks for the email update! Would you mind writing that information here so we have a record?

**Comment by jackstolt** [comment]
Can do! @callahantiff is there anything that you think I left out of our wiki page?

**Comment by callahantiff** [comment]
> Can do! @callahantiff is there anything that you think I left out of our wiki page?

@jackstolt Great job on your first post!

I like your first pass on the Wiki, some thoughts for you to consider:  
- As we move forward, I think it might make sense to create some additional pages. Do you have any ideas on how you might want to organize that material? For example, maybe it would make sense to add pages for:  
  - Relevant Readings  
  - Project Overview  
  - Resources -- something where you 
  - A personal page for each of you to use as a thought board where you created dated entries to track your thoughts and ideas throughout the project

<br>  

**Quick question:** Is someone going to add Luke to the repo?

**Comment by callahantiff** [comment]
@henrylittle21 @jackstolt how are things going?

Can you give me an update on any progress made over the last week? Anything you guys are stuck on or need help with? 

Do we want to meet with this week? I cannot meet tomorrow at 1 pm, but can find other times tomorrow or on Friday. Let me know!

**Comment by jackstolt** [comment]
@callahantiff We finished one of the articles you sent us. Is there anyway to link our google slides presentation, that we are using to take article notes on, to GitHub? I have been pretty busy with a number of college deadlines coming up so I haven't gotten much work done on our wiki or milestones. I don't think a meeting is necessary this week.

**Comment by callahantiff** [comment]
> @callahantiff We finished one of the articles you sent us. Is there anyway to link our google slides presentation, that we are using to take article notes on, to GitHub? I have been pretty busy with a number of college deadlines coming up so I haven't gotten much work done on our wiki or milestones. I don't think a meeting is necessary this week.

Hey @jackstolt - no problem! 😺 

To link your slides, click `share` from the slides view within a browser and copy the URL. Then come back here and paste the URL into a comment.

**Comment by jackstolt** [comment]
@callahantiff Here is the presentation URL: https://docs.google.com/presentation/d/1tSn7aG6yVwKfX9J2ak8HFwYwIUh9y5BjKFTfuIyhifs/edit?usp=sharing

**Comment by callahantiff** [comment]
> @callahantiff Here is the presentation URL: https://docs.google.com/presentation/d/1tSn7aG6yVwKfX9J2ak8HFwYwIUh9y5BjKFTfuIyhifs/edit?usp=sharing

Thanks for sending! I am looking at the slides now. How do you want to proceed? Do you guys want some more time to go over the rest of the list above? Do you want to create a new issue here where we discuss and go into this article in more detail? Let me know what would be the most useful.

Also...what is the Terminator reference for? 😄

**Comment by jackstolt** [comment]
Hey @callahantiff,

@henrylittle21 and I are having a group meeting. Luke is MIA. We need to get the second article done, which we are beginning to work on. The tutorials seem super helpful, but I think will require more time to work through. I added a lot of pages to our wiki, look through them and let me know if there is anything you think we are missing. Hoping that helps provide some structure for our project. The Research Proposal is important and will be continuously worked on. Once we get all of that under control or while we are getting it under control we will start to get a bunch of data, as much as we can.

**Comment by jackstolt** [comment]
@callahantiff the terminator reference was for fun. It was a helpful origin to develop machine learning thoughts and a mascot to keep us motivated. Haha :)

**Comment by callahantiff** [comment]
> Hey @callahantiff,
> 
> @henrylittle21 and I are having a group meeting. Luke is MIA. We need to get the second article done, which we are beginning to work on. The tutorials seem super helpful, but I think will require more time to work through. I added a lot of pages to our wiki, look through them and let me know if there is anything you think we are missing. Hoping that helps provide some structure for our project. The Research Proposal is important and will be continuously worked on. Once we get all of that under control or while we are getting it under control we will start to get a bunch of data, as much as we can.

**WOW!!** 💯 👍 The wiki is really starting to come together and is looking awesome, nice work!! It seems like you guys are getting more comfortable with it, which is really great. Sounds good about working through the articles. Don't worry too much about the tutorials yet, I was thinking that we could meet before you guys started working on those. I will keep an eye on the Wiki as you guys add literature to it and will comment/add additional things that might be helpful.

**PLAN MOVING FORWARD:** Why don't we plan to meet as soon as you guys are done with the second article and the have had a chance to review the links I have included below (they are also mentioned above)? We could use that meeting time to talk about the papers/websites, start thinking through the project objectives, and then make a plan for how to approach the tutorials. What do you think about that plan?

**Comment by jackstolt** [comment]
@callahantiff I think that plan sounds great. We would love to meet tomorrow if that works for you? We just finished up the second article and are ready to learn about the data collection process and whatever prerequisite information you would like to give us for the NLP python tutorials.

**Comment by callahantiff** [comment]
> @callahantiff I think that plan sounds great. We would love to meet tomorrow if that works for you? We just finished up the second article and are ready to learn about the data collection process and whatever prerequisite information you would like to give us for the NLP python tutorials.

Awesome work guys! I would have loved to meet today, but I am actually out of town this week and also next week. I could find a time to meet with you in person on Monday or Tuesday afternoon next week. Would that work?

**TODO:** would you please create 2 new issues? The first issue will be for Python+NLP review and the second for data collection? Then we have a forum to speak about each of those subjects. Sound OK?

**Comment by jackstolt** [comment]
@callahantiff I can totally create those issues. A meeting to discuss the tutorials and data collection would be super helpful. What time is easiest on Monday or Tuesday? We are flexible and can meet either day.

**Comment by callahantiff** [comment]
> @callahantiff I can totally create those issues. A meeting to discuss the tutorials and data collection would be super helpful. What time is easiest on Monday or Tuesday? We are flexible and can meet either day.

@jackstolt - thanks for doing that! If we meet tomorrow it would have to be remotely (via Zoom), but if we meet Tuesday, I could meet in person anytime between 12pm-2pm. Let me know what day you prefer and then we can figure out times. Sound OK?

**Comment by jackstolt** [comment]
@callahantiff Sounds great! Let set up a face-to-face meeting on Tuesday. We are able to meet almost any time in the afternoon, so know which time works best for you.

**Comment by callahantiff** [comment]
> @callahantiff Sounds great! Let set up a face-to-face meeting on Tuesday. We are able to meet almost any time in the afternoon, so know which time works best for you.

@jackstolt - how does 1-2pm at the same place we met last time sound?

**Comment by jackstolt** [comment]
@callahantiff If you think we can accomplish all we need to in an hour then sure! Otherwise, we can try going 12-2 instead

**Comment by callahantiff** [comment]
> @callahantiff If you think we can accomplish all we need to in an hour then sure! Otherwise, we can try going 12-2 instead

@jackstolt - Unfortunately, that's all the time I have tomorrow. This week is tough because I am leaving for a conference Wednesday. We will be able to make some good progress tomorrow, don't worry!

**Comment by jackstolt** [comment]
@callahantiff Alright sounds good. See you tomorrow at 1 pm.

**Comment by callahantiff** [comment]
@jackstolt @henrylittle21 @lajohnson02  - Due to the inclement weather and my desire to keep us all safe and warm today, I am going to change our in person meeting to a Zoom meeting (see Zoom link below). 

**Join Zoom Meeting Here:** https://ucdenver.zoom.us/j/3576659200

The positive part about about this is that I will have more time to meet! **See you virtually at 1pm!**
