### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by jackstolt** [henrylittle21/SRS-NLP#3]
### Everything Data Collection
 All the questions and answers you could ever need:
- How much data: 
- How to textualize:

- [x] Must find out where our data is coming from by Friday
- [ ] Begin Data Collection

Input Data in the [Data Sheet](https://docs.google.com/spreadsheets/d/1Qh5KrIU88KgZJlD5OZ1mGgazQdSgSmTuvRTVu2M-NUw/edit?usp=sharing)

**Comment by callahantiff** [comment]
Hey Guys - I added an example of how to describe one of your data sources to the Wiki ([here](https://github.com/henrylittle21/SRS-NLP/wiki/Data-Gathering)). Let me know if you have any questions!

**Comment by callahantiff** [comment]
Hey guys-

I noticed that you had made some updates to the data collection page of the wiki. Nice work! It looks like you did not include an example of what each of the data sources looked like. Is there anyway that you guys can add that information before we meet this weekend? It will be useful for me as I start to help you with your outline.

Thanks!

**TODO:**  
- [ ] Add example screenshots for each data source to the [Data Gathering](https://github.com/henrylittle21/SRS-NLP/wiki/Data-Gathering) tab of the wiki.

**Comment by jackstolt** [comment]
@callahantiff Yea I did the first part with description and title. I think @lajohnson02 and @henrylittle21  are starting the second part involving the examples. I don't think finishing that wiki page by our meeting will be a problem.

**Comment by callahantiff** [comment]
> @callahantiff Yea I did the first part with description and title. I think @lajohnson02 and @henrylittle21 are starting the second part involving the examples. I don't think finishing that wiki page by our meeting will be a problem.

Sounds good, thanks for the update!

**Comment by callahantiff** [comment]
How's the draft of the email for requesting existing data coming?
